# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev2-test-package',
                'doc_host': 'https://hoangthienan95.github.io',
                'git_url': 'https://github.com/hoangthienan95/nbdev2-test-package',
                'lib_path': 'nbdev2_test_package'},
  'syms': {'nbdev2_test_package.core': {'nbdev2_test_package.core.foo': ('core.html#foo', 'nbdev2_test_package/core.py')}}}
